using System;
using System.Collections.Generic;

namespace PnP.Framework.Modernization.Telemetry.Observers
{
    /// <summary>
    /// Logger that logs to the console output
    /// </summary>
    public class ConsoleObserver : ILogObserver
    {
        private static readonly Lazy<List<Tuple<LogLevel, LogEntry>>> _lazyLogInstance = new Lazy<List<Tuple<LogLevel, LogEntry>>>(() => new List<Tuple<LogLevel, LogEntry>>());
        private bool _includeDebugEntries;
        private string _pageBeingTransformed;

        /// <summary>
        /// Get the single List&lt;LogEntry&gt; instance, singleton pattern
        /// </summary>
        public static List<Tuple<LogLevel, LogEntry>> Logs
        {
            get
            {
                return _lazyLogInstance.Value;
            }
        }

        /// <summary>
        /// Console Observer constructor
        /// </summary>
        public ConsoleObserver(bool includeDebugEntries = false)
        {
            _includeDebugEntries = includeDebugEntries;
        }

        /// <summary>
        /// Output on any warnings generated by the transform process
        /// </summary>
        /// <param name="entry"></param>
        public void Debug(LogEntry entry)
        {
            if (_includeDebugEntries)
            {
                Write($"Debug: [{entry.Heading}] {entry.Message} \n\t Source: {entry.Source} ", ConsoleColor.Magenta);
            }
        }

        /// <summary>
        /// Errors 
        /// </summary>
        /// <param name="entry"></param>
        public void Error(LogEntry entry)
        {
            var error = entry.Exception != null ? entry.Exception.Message : "No error logged";
            
            if (!_includeDebugEntries) { 
                Write($"Error: [{entry.Heading}] {entry.Message} Error: { error }", ConsoleColor.Red);
            }
            else
            {
                var stackTrace = entry.Exception != null ? entry.Exception.StackTrace : "No trace logged";
                Write($"Error: [{entry.Heading}] {entry.Message} Error: { error } StackTrace: { stackTrace }", ConsoleColor.Red);
            }
        }

        /// <summary>
        /// Output a summary to the console
        /// </summary>
        public void Flush()
        {
            Flush(true);
        }

        /// <summary>
        /// Output a summary to the console
        /// </summary>
        /// <param name="clearLogData">Also clear the log data</param>
        public void Flush(bool clearLogData)
        {
            //Output transform duration
            Console.WriteLine("-----------Transformation Summary -------------");

            Logs.ForEach(o =>
            {
                Write($"-  {o.Item2.Message}", ConsoleColor.Cyan);
            });

            Console.WriteLine("-----------------------------------------------");

            if (clearLogData)
            {
                var logs = _lazyLogInstance.Value;
                logs.RemoveRange(0, logs.Count);
            }
        }

        /// <summary>
        /// Output on operations throughout the transform process
        /// </summary>
        /// <param name="entry"></param>
        public void Info(LogEntry entry)
        {
            // Log summary data for final output
            if(entry.Heading == LogStrings.Heading_Summary)
            {
                Logs.Add(new Tuple<LogLevel, LogEntry>(LogLevel.Information, entry));
            }
            else
            {
                Write($"[{entry.Heading}] {entry.Message}");
            }
        }

        /// <summary>
        /// Output on any warnings generated by the transform process
        /// </summary>
        /// <param name="entry"></param>
        public void Warning(LogEntry entry)
        {
            
            Write($"Warning: [{entry.Heading}] {entry.Message}", ConsoleColor.Yellow);
        }

        /// <summary>
        /// Sets the id of the page that's being transformed
        /// </summary>
        /// <param name="pageId">Id of the page</param>
        public void SetPageId(string pageId)
        {
            this._pageBeingTransformed = pageId;
        }

        /// <summary>
        /// Cental method to output to console
        /// </summary>
        /// <param name="message"></param>
        public void Write(string message, ConsoleColor color = ConsoleColor.White)
        {
            message = message.Replace(LogStrings.KeyValueSeperatorToken, "=");
            
            var originalColour = Console.ForegroundColor;
            Console.ForegroundColor = color;
            Console.WriteLine(message);
            Console.ForegroundColor = originalColour;
        }        
    }
}
