### YamlMime:ManagedReference
items:
- uid: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  commentId: N:PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  id: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  children:
  - PnP.Framework.Provisioning.Model.Configuration.SiteSecurity.ExtractConfiguration
  langs:
  - csharp
  - vb
  name: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  nameWithType: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  fullName: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  type: Namespace
  assemblies:
  - PnP.Framework
references:
- uid: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity.ExtractConfiguration
  commentId: T:PnP.Framework.Provisioning.Model.Configuration.SiteSecurity.ExtractConfiguration
  parent: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  name: ExtractConfiguration
  nameWithType: ExtractConfiguration
  fullName: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity.ExtractConfiguration
- uid: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  commentId: N:PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  name: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  nameWithType: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
  fullName: PnP.Framework.Provisioning.Model.Configuration.SiteSecurity
